#!/usr/bin/env bash
#
# Give a git worktree its own host port mapping for Sail.
#
# Usage:
#   scripts/worktree-env.sh <worktree-dir> <slot> [--dev] [--force]
#
#   <worktree-dir>  absolute or relative path to the worktree checkout
#   <slot>          1-4; each slot maps to a distinct set of host ports
#   --dev           also set APP_ENV=local and APP_DEBUG=true (optional)
#   --force         overwrite an existing .env (backed up to .env.bak)
#
# This copies .env.example into the worktree's .env and appends only the
# host-forwarding variables (APP_PORT, VITE_PORT, FORWARD_*). Service ports
# INSIDE the container (DB_PORT, REDIS_PORT, MAIL_PORT, AWS_ENDPOINT_URL)
# are reachable by hostname within the compose network and must NOT be
# changed -- they stay at their .env.example values.
set -euo pipefail

WT_DIR="${1:-}"
SLOT="${2:-}"
APP_ENV_MODE="example"
FORCE=0

for arg in "$@"; do
    case "$arg" in
        --dev) APP_ENV_MODE="dev" ;;
        --force) FORCE=1 ;;
    esac
done

if [[ -z "$WT_DIR" || ! "$SLOT" =~ ^[1-4]$ ]]; then
    echo "usage: $0 <worktree-dir> <slot 1-4> [--dev] [--force]" >&2
    exit 1
fi

# Slot -> port table (host side only)
declare -A APP_PORT=([1]=8081 [2]=8082 [3]=8083 [4]=8084)
declare -A VITE_PORT=([1]=5174 [2]=5175 [3]=5176 [4]=5177)
declare -A DB_PORT=([1]=5433 [2]=5434 [3]=5435 [4]=5436)
declare -A REDIS_PORT=([1]=6380 [2]=6381 [3]=6382 [4]=6383)
declare -A MINIO_PORT=([1]=9001 [2]=9002 [3]=9003 [4]=9004)
declare -A MINIO_CONSOLE_PORT=([1]=8901 [2]=8902 [3]=8903 [4]=8904)
declare -A MAILPIT_PORT=([1]=1026 [2]=1027 [3]=1028 [4]=1029)
declare -A MAILPIT_UI_PORT=([1]=8026 [2]=8027 [3]=8028 [4]=8029)

ENV_FILE="$WT_DIR/.env"
EXAMPLE_FILE="$WT_DIR/.env.example"

if [[ ! -f "$EXAMPLE_FILE" ]]; then
    echo "error: no .env.example in $WT_DIR" >&2
    exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
    if [[ "$FORCE" -eq 1 ]]; then
        cp "$ENV_FILE" "$ENV_FILE.bak"
        echo "existing .env backed up to $ENV_FILE.bak"
    else
        echo "error: $ENV_FILE already exists (use --force to replace)" >&2
        exit 1
    fi
fi

cp "$EXAMPLE_FILE" "$ENV_FILE"

sed -i "s|^APP_URL=.*|APP_URL=http://localhost:${APP_PORT[$SLOT]}|" "$ENV_FILE"

if [[ "$APP_ENV_MODE" == "dev" ]]; then
    sed -i "s|^APP_ENV=.*|APP_ENV=local|" "$ENV_FILE"
    sed -i "s|^APP_DEBUG=.*|APP_DEBUG=true|" "$ENV_FILE"
    sed -i "s|^SESSION_SECURE_COOKIE=.*|SESSION_SECURE_COOKIE=false|" "$ENV_FILE"
fi

cat >> "$ENV_FILE" <<EOF

# --- worktree slot ${SLOT} host port mapping (generated by worktree-env.sh) ---
APP_PORT=${APP_PORT[$SLOT]}
VITE_PORT=${VITE_PORT[$SLOT]}
FORWARD_DB_PORT=${DB_PORT[$SLOT]}
FORWARD_REDIS_PORT=${REDIS_PORT[$SLOT]}
FORWARD_MINIO_PORT=${MINIO_PORT[$SLOT]}
FORWARD_MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT[$SLOT]}
FORWARD_MAILPIT_PORT=${MAILPIT_PORT[$SLOT]}
FORWARD_MAILPIT_UI_PORT=${MAILPIT_UI_PORT[$SLOT]}
EOF

echo "wrote $ENV_FILE (slot $SLOT, app ${APP_ENV_MODE})"
if ! grep -q "^APP_KEY=.\{20,\}" "$ENV_FILE"; then
    echo "WARNING: APP_KEY is empty. Run in the worktree after sail up:"
    echo "  sg docker -c \"cd $WT_DIR && ./vendor/bin/sail artisan key:generate\""
fi
echo "  app:        http://localhost:${APP_PORT[$SLOT]}"
echo "  vite:       ${VITE_PORT[$SLOT]}"
echo "  postgres:   ${DB_PORT[$SLOT]}"
echo "  redis:      ${REDIS_PORT[$SLOT]}"
echo "  minio:      ${MINIO_PORT[$SLOT]} / console ${MINIO_CONSOLE_PORT[$SLOT]}"
echo "  mailpit:    smtp ${MAILPIT_PORT[$SLOT]} / ui ${MAILPIT_UI_PORT[$SLOT]}"
echo "never change: DB_PORT, REDIS_PORT, MAIL_PORT, AWS_ENDPOINT_URL (in-container hostnames)"
